on:
  push:
    branches:
      - test

name: Test - Build and Deploy

jobs:
  build-and-deploy:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build Javascript
        run: |
          npm run build
      - name: Publish package to npm
        run: |
          npm publish ./pkg --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN2 }}
